/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimePresenter.java
 *
 * Created on Mar 13, 2012, 6:44:50 PM
 */
package iplanner_v2;

import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author tishan
 */
public class TimePresenter extends javax.swing.JFrame {
private static String selectedTimeSlot;
private static boolean isSelected = false;

    /**
     * @return the selectedTimeSlot
     */
    public static String getSelectedTimeSlot() {
        return selectedTimeSlot;
    }

    /**
     * @return the isSelected
     */
    public static boolean isSelected() {
        return isSelected;
    }
    /**
     * Creates new form TimePresenter
     */
    public TimePresenter(ArrayList<String> timeSlots) {
        try {
            UIManager.setLookAndFeel(new com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setTitle("iPlanner -> Suggestions");
        setLocationRelativeTo(null);

        suggestTime(timeSlots.get(0), timeSlots.get(1), timeSlots.get(2));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        time1 = new javax.swing.JRadioButton();
        time2 = new javax.swing.JRadioButton();
        time3 = new javax.swing.JRadioButton();
        day = new javax.swing.JLabel();
        accept = new javax.swing.JButton();
        Cancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("These are the sugested time slots for your meeting");

        buttonGroup1.add(time1);
        time1.setSelected(true);
        time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(time2);

        buttonGroup1.add(time3);

        accept.setText("Accept");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });

        Cancle.setText("Cancle");
        Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(time3)
                            .addComponent(time1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(time2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(day)
                            .addComponent(jLabel1))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(accept)
                .addGap(18, 18, 18)
                .addComponent(Cancle)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(time1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(time2)
                .addGap(3, 3, 3)
                .addComponent(time3)
                .addGap(36, 36, 36)
                .addComponent(day)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accept)
                    .addComponent(Cancle))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time1ActionPerformed

    private void CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_CancleActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        selectedTimeSlot = buttonGroup1.getSelection().getActionCommand();
        this.setVisible(false);       
        NewMeeting.setTestField(selectedTimeSlot); 
        System.out.println("> "+selectedTimeSlot);
        NewMeeting.setBtnStatus(true);
        isSelected = true;
    }//GEN-LAST:event_acceptActionPerformed

    /**
     * @param args the command line arguments
     *
     * public static void main(String args[]) {
     * java.awt.EventQueue.invokeLater(new Runnable() { public void run() { new
     * TimePresenter().setVisible(true); } });
    }
     */
    public void suggestTime(String timeA, String timeB, String timeC) {
        time1.setText(timeA);
        time1.setActionCommand(timeA);
        time2.setText(timeB);
        time2.setActionCommand(timeB);
        time3.setText(timeC);
        time3.setActionCommand(timeC);
        //day.setText("Suggested day for Your meeting is "+dayStr+"\n Select a prefered time slot and press accept to select a date for the meeting. ");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancle;
    private javax.swing.JButton accept;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel day;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton time1;
    private javax.swing.JRadioButton time2;
    private javax.swing.JRadioButton time3;
    // End of variables declaration//GEN-END:variables
}
